ARG PG_VERSION
FROM postgres:${PG_VERSION}
LABEL author="John, johnmoscoso911@gmail.com"

# RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.utf8
ENV TZ America/Guayaquil
ENV LANG en_US.utf8
