services:
  zookeeper-container:
    image: zookeeper:3.4.9
    hostname: zookeeper-container
    container_name: zookeeper-container
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper-container:2888:3888
    restart: always

  kafka-broker:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka-broker
    container_name: kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-broker:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-container:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=ERROR,kafka.producer.async.DefaultEventHandler=ERROR,state.change.logger=ERROR"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper-container
    restart: always

  entities:
    container_name: entities
    build:
      context: entities
      dockerfile: Dockerfile.jvm
    ports:
      - "8091:8091"
      - "8491:8491"
    environment:
      PG_URL: ${PG_URL}
      PG_USER: ${PG_USER}
      PG_PWD: ${PG_PWD}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      OIDC_SERVER_URL: ${OIDC_SERVER_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_TRUST_STORE_FILE: ${OIDC_TRUST_STORE_FILE}
      OIDC_TRUST_STORE_PWD: ${OIDC_TRUST_STORE_PWD}
      CERT_FILE: ${CERT_FILE}
      CERT_KEY: ${CERT_KEY}
    depends_on:
      - kafka-broker
    restart: unless-stopped

  core:
    container_name: middleware
    build:
      context: core
      dockerfile: Dockerfile.jvm
    ports:
      - "8090:8090"
      - "8490:8490"
    environment:
      PG_URL: ${PG_URL}
      PG_USER: ${PG_USER}
      PG_PWD: ${PG_PWD}
      MONGO_URL: ${MONGO_URL}
      MONGO_DB: ${MONGO_DB}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
      MQTT_USER: ${MQTT_USER}
      MQTT_PASSWD: ${MQTT_PASSWD}
      OIDC_SERVER_URL: ${OIDC_SERVER_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_TRUST_STORE_FILE: ${OIDC_TRUST_STORE_FILE}
      OIDC_TRUST_STORE_PWD: ${OIDC_TRUST_STORE_PWD}
      CERT_FILE: ${CERT_FILE}
      CERT_KEY: ${CERT_KEY}
    depends_on:
      - kafka-broker
    restart: unless-stopped
